### ISSUE TITLE
Suggestions for README

### ISSUE THREAD

**Issue by sophiemeakin** [epiforecasts/EpiNow2#106]
Additional suggested changes to README 'Quick Start' guide, all generally related to signposting towards further details:
- There is no mention of `forecast_infections` after highlighting it as a core function in the 'Quick start' section; suggest adding at least one sentence and some explicit signposting towards further details in the function documentation.
- Add signposting towards interpreting the summary table output from `epinow` and `regional_epinow`. It is not clear to me what the estimate_numeric column shows; also could clarify what is shown in estimate column (median and bottom/top?); how is the 'Expected change in daily cases' determined?
- Add signposting towards details of methods to help with interpreting summary plots (estimate vs. estimate based on partial data).
- Clarify that the output from `regional_epinow` is essentially the same as `epinow`, but by region.
- Cosmetic: in function documentation, the y-axis labels are overlapping in the example summary plots with A, B, C subplots (e.g. [here](https://epiforecasts.io/EpiNow2/reference/report_plots.html)).

**Comment by seabbs** [comment]
Thanks @sophiemeakin all good comments. 

Ah oops the `estimate_numeric` column should be dropped when showing the table (its used internally to make the summary table + plots). 

Good idea on explanation - I have mainly been assuming people have seen the website and are coming from there but definitely need to grow these docs into there own thing. 

On the overlapping plots the only solution to that I see is to change the size that plots are rendered at (which happens when the site is built using `pkgndown::build_site`). I have nooooo idea how to do that 😆  - will have a look around. On the plots in the docs do you think its helpful printing the output - the other solution is to just let people do it themselves. 

For `forecast_infections` I might just drop the mention as its using functionality we aren't using at the mo and hence is not really being developed (plan is to look at more later as it offers some potentially easy ways of testing a massive number of models without having to code them all in stan). 

Good idea on broadcasting what `regional_epinow` is actually doing!

**Comment by seabbs** [comment]
Just merged in so closing - thanks again.
