### ISSUE TITLE
`estimate_infections.stan` occasionally throws exceptions with large numbers in the negative binomial

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#143]
This likely indicates an issue with the model set up and may be linked to a stan code bug. Alternatively it may just be due to model complexity and controls within the stan code should be implemented to deal with it.

**Comment by medewitt** [comment]
Some of this might be the ratio of mu and phi overflowing integers, which makes it a little hard to debug[see Stan docs](https://mc-stan.org/docs/2_25/functions-reference/nbalt.html#stan-functions-13)

**Comment by jhellewell14** [comment]
I get this error from running the example code for the latest build in the repo.

`[2] "  Exception: Exception: neg_binomial_2_rng: Random number that came from gamma distribution is 1.33651e+09, but must be less than 1.07374e+09  (in 'functions/generated_quantities.stan' at line 17; included from 'model_estimate_infections' at line 8)"
[3] "  (in 'model_estimate_infections' at line 118)" `

It's weird because the example code only has about 6000 reported cases max, so it shouldn't be hitting the overflow limit.

**Comment by jhellewell14** [comment]
I think it's because you have accidentally deleted the prior for `rep_phi` while functionalising the stan code

**Comment by jhellewell14** [comment]
I'm putting together a PR to fix this and also implement a different prior as in: https://github.com/epiforecasts/EpiNow2/issues/121

**Comment by seabbs** [comment]
It should be called here: https://github.com/epiforecasts/EpiNow2/blob/5304ebe99877e948bf3ced029bf752ae894ee196/inst/stan/functions/observation_model.stan#L22

Which is apprently fine but maybe not (and I agree is quite hidden). I tested the prior in #121 and saw quite poor results (i.e lots of divergent transitions but maybe failed to do it well. 

Very keen to see a PR to resolve 😄

**Comment by jhellewell14** [comment]
Does anyone use the Poisson model? Why not just bin it?

**Comment by seabbs** [comment]
I think there is very strong argument its the one we should be using as a default so need to keep as an option + for testing.

**Comment by jhellewell14** [comment]
My error is from running this:
`library(EpiNow2)

reporting_delay <- bootstrapped_dist_fit(rlnorm(1000, log(3), 1), max_value = 15,bootstraps = 1)


generation_time <- get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
incubation_period <- get_incubation_period(disease = "SARS-CoV-2", source = "lauer")


reported_cases <- example_confirmed[1:80]
head(reported_cases)

estimates <- epinow(reported_cases = reported_cases,
                    generation_time = generation_time,
                    delays = list(incubation_period, reporting_delay))`

**Comment by jhellewell14** [comment]
From this line: https://github.com/epiforecasts/EpiNow2/blob/5304ebe99877e948bf3ced029bf752ae894ee196/inst/stan/functions/generated_quantities.stan#L17

**Comment by seabbs** [comment]
So is this an edge case for the gamma distribution PMF? This recently had its exceptions updated from > to >= and that may be causing issues?

**Comment by seabbs** [comment]
yes - unfortunately the error can occur here but actually be driven by something further up which is annoying.

 If reports are spuriously high then overdispersion might be putting you over the top of the max in some edge cases. I agree reducing overdispersion or tuning down the reports max should resolve. Longer term id why it sometimes allows such high reports is a good idea as this is definitely not behaviour we want. 

If you set the logic gate to 1e7 does it go away?

**Comment by hsbadr** [comment]
@seabbs @jhellewell14 May you test if PR #147 fixes this for you?

`Exception: neg_binomial_2_rng: Random number that came from gamma distribution is ..., but must be less than 1.07374e+09`

**Comment by jhellewell14** [comment]
#147 does fix the problem but I personally would prefer to fix this by figuring out why `rep_phi` is so large and whether that is sensible behaviour or not (and could be fixed with a better prior).

**Comment by hsbadr** [comment]
@jhellewell14 I agree in principle. Though, I think it's inevitable to get large `phi` (dividing by small numbers, exponential, numerical instability, ... etc), especially during **warmup**. I believe that's why the fallback is hardcoded in the `math` library (see [stan-dev/math#466](https://github.com/stan-dev/math/pull/466)). The good news is that #147 temporarily bypasses the errors during **warmup**, just like clipping the large reports (`> 1e8`):
`sampled_reports[s] = neg_binomial_2_rng(reports[s] > 1e8 ? 1e8 : reports[s], rep_phi[model_type]);`

**Comment by jhellewell14** [comment]
I'd be less concerned if it a) it hadn't just started happening since splitting the stan model into functions and b) wasn't happening on a dataset where there are maximum ~ 6000 daily cases. Definitely seems like we shouldn't be hitting any kind of integer overflows on reports with numbers that small.

**Comment by hsbadr** [comment]
I see. I agree that functionalizing the `stan` code has introduced issues that should be fixed first, regardless of #147 which would catch occasional exceptions with large `phi`.

**Comment by medewitt** [comment]
I was seeing this error before the functionalisation as well in a variety of scenarios (some unit areas where there were waves of cases report (perhaps blowing up over dispersion) and some larger case counts). Might be worth coding up a known DGP and run over grid of dispersions. Might have time later this week...

**Comment by hsbadr** [comment]
@medewitt I tun into similar issues earlier too, but they're more frequent now. From my testing, the overflows/exceptions are due to exploded reciprocal overdispersion parameter (`phi`) not the cases, especially during warmup. That's why #147 works for me. But, admittedly, it catches the exceptions instead of fixing the culprit. 

So, @seabbs, I think a good start to fix this is to trace `rep_phi` and maybe set its upper bound.

**Comment by hsbadr** [comment]
@medewitt I run into similar issues earlier too, but they're more frequent now. From my testing, the overflows/exceptions are due to exploded reciprocal overdispersion parameter (`phi`) not the cases, especially during warmup. That's why #147 works for me. But, admittedly, it catches the exceptions instead of fixing the culprit. 

So, @seabbs, I think a good start to fix this is to trace `rep_phi` and maybe set its upper bound.

**Comment by seabbs** [comment]
I also saw this issue early and think its unlikely to be related to functionalising the code. @hsbadr checking out #147 now. @jhellewell14 agree a fix is better than a catch but a catch will do in the short term. Unfortunately I have no dev time for this in the next few days as responding to some policy maker requests but very (very very) happy to see more exploration of this. 

Has anyone been able to make a simple example that always throws this issue if uncaught? For me it was been quite stochastic and hence hard to debug.

**Comment by jhellewell14** [comment]
I am finding that this always throws the issue for me: https://github.com/epiforecasts/EpiNow2/issues/143#issuecomment-718856436

**Comment by jhellewell14** [comment]
Also yes lets do the catch for now and figure out later

**Comment by seabbs** [comment]
Odd that works as advertised for me - will review later. Another option is to move all estimate generation out of the model fitting making use of #150  or similar. This would obviously help increase fitting speeds as well.

**Comment by hsbadr** [comment]
Agreed. The catch is important either way. Maybe, later when you've time to debug this, add an option to turn it off `if debug = TRUE`.

Also, the results depend on the `stan` version and backend as well as the OS. So, debugging needs to be done for different machines.

**Comment by seabbs** [comment]
Reopening as root cause not totally resolved. Started looking at this in more detail. Might be sensible to look at the differences between the Poisson and negative binomial model as the NB model may be hiding some underlying issue that the poisson exposes (as it has less flexibility to fit to observed data). If interested can explore using the `family` argument.

**Comment by hsbadr** [comment]
Can you check it we get zero or infinite or unintialized `cases` or `rep_phi` (`zero`, `Inf`, `-Inf`, or `nan`) when calling `report_rng()` or `report_lp()`? What happens if you update the condition `if (rep_phi[model_type] > 1e4)` to catch those as well (not only large values)?
