### ISSUE TITLE
epinow() fails if reported_cases is a data.frame instead of a data.table

### ISSUE THREAD

**Issue by johnaponte** [epiforecasts/EpiNow2#36]
I think documentation of epinow() function must be updated to state that the reported_cases parameter must be a data.table and not a data.frame as it is currently stated. 
A check of that condition would be worth.
It took me hours to find where the 
```
Error in `>=.default`(date, min(estimate$date, na.rm = TRUE)) : 
  comparison (5) is possible only for atomic and list types
```
comes from.

Thanks.

John Aponte

**Comment by seabbs** [comment]
Hi John, 

Thanks for flagging this (see #35 for some more exploration of the issue) and putting in the time to identify the issue. 

The plan is to start doing some internal conversion so that native data frames and tibbles will be supported. Will close this once implemented (likely end of today). 

Sam
