### ISSUE TITLE
lintr warning

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#402]
e.g. in https://github.com/epiforecasts/EpiNow2/actions/runs/5071088533/jobs/9107030665#step:7:17

```
Warning message:
In modify_defaults(..., defaults = tagged_linters) :
  Trying to remove ‘indentation_linter’, which is not in `defaults`.
```

**Comment by Bisaloo** [comment]
This happens because the indentation_linter is part of lintr dev version but by default, lintr CRAN version is installed:

https://github.com/epiforecasts/EpiNow2/blob/0c1aef7056c6592a8bd232bd7762df738ef6b057/.github/workflows/lint-only-changed-files.yaml#L26

You can either ignore this warning until this change is pushed to CRAN or force install lintr dev version:

```diff
          extra-packages: |
            any::gh
-           any::lintr
+           r-lib/lintr
            any::purrr
```

**Comment by sbfnk** [comment]
Seems to be resolved in the latest version of lintr
