### ISSUE TITLE
create `gt_opts` as an alias for `generation_time_opts`

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#564]
As we move towards extending the `_opts` interface to specifying the data and preprocessing (#346) we are adding complexity to the user interaction. Where in the past a user would have written something like:

```r
epinow(reported_cases = cases, generation_time = list(mean = 3, sd = 1))
```
we're moving towards requiring
```r
epinow(
  data = data_opts(cases),
  generation_time = generation_time_opts(Gamma(mean = 3, sd = 1)))
)
```

I'm wondering if we should provide a simpler version where if any of the arguments requiring an `_opts` helper function are not specified using said helper functions we should call it for the user and pass on the first argument. This would enable the user to specify some of their desired (e.g. case data, generation time) without being exposed to the full interface.

This would mean that one could write
```r
epinow(data = cases, generation_time = Gamma(mean = 3, sd = 1))
```
with the same results as the calls above.

**Comment by jamesmbaazam** [comment]
I believe we moved towards enforcing the use of the `*_opts()` interface because of situations where wrong options are passed to an argument like pointed out here https://github.com/epiforecasts/EpiNow2/issues/337#issuecomment-1420621618. If we are to go by the suggestion here, I wonder if we are not putting that burden on ourselves to ensure that the right arguments are passed. It could also lead to unexpected bugs in nuanced cases like the generation time vs delays argument options.

I think the current interface may be verbose but it forces the user to make intentional choices and makes its consequence easier to debug as well.

**Comment by seabbs** [comment]
> I'm wondering if we should provide a simpler version where if any of the arguments requiring a

Could we provide some short aliases for the annoyingly long ones

**Comment by sbfnk** [comment]
> > I'm wondering if we should provide a simpler version where if any of the arguments requiring a
> 
> Could we provide some short aliases for the annoyingly long ones

yes could have `gt_opts()` map to `generation_time_opts()` as the main culprit. Or perhaps even rename it? Would then also have to rename the argument if wanting to keep the consistent `arg = arg_opts()` structure.

Just to try it out, it would make:
```r
epinow(
  data = data_opts(cases),
  gt = gt_opts(Gamma(mean = 3, sd = 1)))
)
```
Clarity vs brevity, what do people think?

**Comment by seabbs** [comment]
Personally I like the idea of an alias here but keep the descriptive arg name.
