### ISSUE TITLE
Using onset date instead of date of report

### ISSUE THREAD

**Issue by munozedg** [epiforecasts/EpiNow2#61]
Question: Can I use `onset date` instead of  `reporting date` in my analysis? Any recommendations on the interpretation of the results obtained when using `onset date`?

**Comment by seabbs** [comment]
Hi @munozedg, 

Yes, that shouldn't be a problem just supply a single incubation delay rather than both an incubation delay and a reporting delay. 

The interpretation of infections + Rts etc should be the same but you will be forecasting/fitting to onsets rather than reported cases. The estimate may well be more accurate than when based on reported cases as you are "closer" to the infection process when using onsets.  If interested in getting a reported case forecast from that you could, for example, use this fn: https://epiforecasts.io/EpiNow2/reference/adjust_infection_to_report.html

If you only have partial-onset data (which I imagine is likely) you may have some issues due to missing data. The options we have considered so far here are to either 1. fit too reported cases and use your good data on onsets to parameterize a very robust onset to report delay distribution or 2. Impute missing onsets before using `EpiNow2` on onsets.  

In the future, we plan to support fitting too multiple datasets at once (i.e onsets and reported cases for example) but this is still in development at the moment, unfortunately. 

Hope that helps, 

Sam

**Comment by munozedg** [comment]
Thanks for your quick response!
PS-Sure! I will consider sharing the analysis & data
