### ISSUE TITLE
update link to guide on how to install Rtools on Windows

### ISSUE THREAD

**Issue by avallecam** [epiforecasts/EpiNow2#637]
The currently linked guide suggests I install `Rstan`; is that action needed to install Rtools? or fresh users may need to install `Rstan` too?

https://github.com/epiforecasts/EpiNow2/blob/3b2a10dc6bf39dbc62b498a328ca2f0ea5818dc2/README.Rmd#L102-L104

I found a plain installation guide at http://jtleek.com/modules/01_DataScientistToolbox/02_10_rtools/#1

I plan to add four steps on the tutorial setup websites to solve this issue reported by one workshop participant https://github.com/epiverse-trace/tutorials-middle/issues/55

**Comment by jamesmbaazam** [comment]
> The currently linked guide suggests I install Rstan; is that action needed to install Rtools? or fresh users may need to install Rstan too?

Hi @avallecam Windows users generally need to install Rtools to install/build other packages (that need compilation at some point), so maybe that's why they were getting an error when installing Rstan. 

In the link in the README here, the section on (Configuring the C toolchain)[https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain] has a section on Windows that explains how to install Rtools.

In the tutorials, you may have to provide the steps for Windows users in that order, i.e., Check that rtools is installed using devtools, else install rtools and confirm it works by installing and using devtools to check, then install RStan.

Hope this clarifies this issue. If so, we can close it as resolved.

**Comment by avallecam** [comment]
Thank you for the clarification. Now, I have managed to find the instructions for Windows. 

I would suggest that if the paragraph in the README is exclusive to Windows users, then, the link could refer directly to the "C toolchain to Windows". However, the installation of a version of Rtools depends on the local version of R, so possibly a clearer link could refer to this link https://cran.r-project.org/bin/windows/Rtools/.

For me this issue is resolved, but I would leave this suggestion to your consideration.

**Comment by jamesmbaazam** [comment]
Thanks, Andree. I think we are better off generalizing it to all operating systems because I also had to set up the C++ toolchain on my new MacBook and it was quite difficult for someone coming from Windows.
