### ISSUE TITLE
Improving logging usability. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#89]
The current logging system treats information from every level of the package as equal. When running across many regions (i.e as done [here](https://github.com/epiforecasts/covid-rt-brazil-subregional)) this becomes a problem as log noise overwhelms its usability (exacerbated by noise from stan when `furure = TRUE`). 

It would greatly help if summary logs produced by `regional_epinow` etc were split from region level logs produced by `epinow` etc. This would enable users to get an overview of how their estimates were performing from the `regional_epinow` log (i.e % of regions complete (might be hard due to parallel processing), summary of successes, a summary of failures, a summary of regions with warnings etc). This would be in the style of the logging introduced in #84. Potentially this change could be linked to adding processing output as used to track estimates in `epiforecasts/covid-rt-estimates` by @joeHickson.

**Comment by joeHickson** [comment]
% of regions complete would be hard - all the regions are to be treated as isolated parallel code so whilst we can see each complete early in the logs it's only when they all complete that the code that knows about all the regions resumes. As such a "region 7/24 processed" is hard to achieve (although I'm sure there must be techniques somewhere). At present you can see the region start / end in the overall log which whilst getting cluttered for large regions combined with CPU usage gives an indication of process (e.g. global data set, 100% cpu usage, last region to start = Mexico => probably about 1/2 way through, 3 cores used, last started = Zimbabwe => all started, waiting on final 3 to finish).

We have discussed splitting the individual regions more out into a task management pool but we have shelved for review later as a lot of work and one to consider the justification for later. It would give finer grained control of the task list (you could query it to get progress status) and you could run on a bigger fleet of smaller machines (1 box per region rather than per dataset) which would probably save money as at the moment a big box is mostly idle whilst waiting on the few slow regions. It also require restructuring as the summary is then a separate job to run once all the individual regions have processed.

Something that should hopefully happen is that each level gets a different message structure to identify the level:
[date] [level]: [message] = top level outer wrapper (e.g. covid-rt-estimates) level message - this is how messages are configured to appear by default.
[date] [level] [dataset]: [message] = dataset level problem (this is configured by wrapping the epinow call with  try/catch/withcallinghandlers https://github.com/epiforecasts/covid-rt-estimates/blob/master/R/run-region-updates.R#L79  )
[date] [level] [region]: [message] = region level problem (this is applied within the epinow library in the same fashion as the dataset level - https://github.com/epiforecasts/EpiNow2/blob/master/R/epinow.R#L453 )

I am aware some of the trace / debug / info messages don't yet follow this pattern. It is possible to namespace the log files (e.g. include program name in the log message) but I don't think it actually gives you anything over top level / dataset / region. It is an area to review if there's an alternative way of giving the context to the logger.

Rather than split logs further the approach I am currently working towards is getting them ingested into a log processing tool (as we're running on azure I'm going for Log Analystics but the same should be true on AWS Cloudwatch and Google's Cloud Logging). These tools then let you slice, dice and filter your data.

**Comment by joeHickson** [comment]
Given the 1577 locations in the Brazil city dataset we may need to get that queue in to allow it to process in any reasonable time frame. That is an order of magnitude tougher than anything else that has been processed!

**Comment by seabbs** [comment]
For the brazil example, we are using an approximate approach that runs in 1/100 ~ 1/1000th of the time so it is actually manageable on a 4 core server in a few hours (which was the target given by the downstream users but is not stable enough for widespread use).

The suggestion here is not a log per region and an overarching log but rather having an internal log for all regions and an overview log (that gets printed to the console) which is the first thing users actually interact with and is the only thing returned by default (with additional logs returned via an arg of some kind). The current setup produces too much noise and will likely overwhelm new users.

I agree with the notes for `covid-rt-estimates` but this change is mainly for other users/other applications in mind (none of who will have access to that infrastructure). 

Any changes made here will still enable users to have a single log file and hence keep the framework in `covid-rt-estimates` working. 

Planned implementation is: 

```
regional_epinow(internal_log = NULL) {
....
if (is.null(internal_log)) {
internal_log <- paste0(tempdir(), "info.log")
flog.info("Internal logs stored at: %s", internal_log)
} 
....

run_model <- function(internal_log) { 
# does this respect R's function hierarhcy or will it set globally? If set globall can the previous state be saved and restored?
flog.append(internal_log)
}

# Add logging measures to give failure, success, warning summarises across regions
```

**Comment by joeHickson** [comment]
we might be able to achieve this relatively simply by setting different logging verbosity levels for screen  vs file - most loggers support it. Screen would then get info, log file would vary based on logging level flag
