### ISSUE TITLE
Reduce function arguments

### ISSUE THREAD

**Issue by hsbadr** [epiforecasts/EpiNow2#95]
It may be cleaner to combine all outputs that user can select to return/save into a vector of character strings; something like:
`outputs = c("fit", "estimates", "partial", "samples", "plots")`
replacing the five arguments:
`return_fit = TRUE`,
`return_estimates = TRUE`,
`return_partial_estimates = TRUE`,
`keep_samples = TRUE`, and 
`make_plots = TRUE`.
The user can select any subset of outputs (e.g.,  `outputs = c("estimates", "plots")` to get the estimates and plots only).

This could be based on @joeHickson's comment about magic strings (see #87).

**Comment by seabbs** [comment]
Thanks for opening this - be good to canvas opinion. 

I really like this idea as the current setup is pretty clunky and will only get worse if more switches for output need to be added.

However, as @joeHickson has pointed out the downside may be that if users misspell a character string they will not get the output they were expecting. My preference would probably be to use this approach, check the strings for arguments that aren't expected, and then throw an error if they are found.

**Comment by hsbadr** [comment]
@seabbs I see. A workaround for this that is to match the user supplied `outputs` with the full list of outputs (`outputs_all`) using `str_subset` and `map` functions from `purrr` and `stringr` packages, respectively:
```
outputs <- c("part", "sampl", "dumb", "estim")
outputs_all = c("fit", "estimates", "partial", "samples", "plots")

library(purrr)
library(stringr)

outputs_match <- map(
  outputs,
  str_subset,
  string = outputs_all
) %>% 
  compact() %>% 
  flatten_chr() %>% 
  unique()
```

Then, use `outputs_match` which returns `c("partial", "samples", "estimates")`, for the above example. You may also verbose the matched outputs and warn the users if they provided nonsense.

**Comment by seabbs** [comment]
Yes, that sounds like a good solution - though probably throw an error rather than a warning I think. @joeHickson thoughts? I realise this is still magic strings but I think will really help clean up the interface. 

I am trying to stabilize the interface with the next CRAN release which I'm trying to get out by the end of the week so would be good to reach a decision on this.

**Comment by joeHickson** [comment]
fine by me. If that list of outputs_all is available then you can use it as shorthand for injecting the full list (rather than re-writing it out). Make sure it's documented and it should be clear enough. Possibly add a safety test that you have as many items in your list after validating it and if not raise an error.

**Comment by hsbadr** [comment]
Sounds good!

@seabbs If you'd like to use the above code, or a variant of it, using the pipe operator (which I do prefer for code readability), you'll need to add the following to the `NAMESPACE`:
```
importFrom(purrr, "%>%")
importFrom(stringr, "str_subset)
```
You may also expand every function argument on a new line.

**Comment by seabbs** [comment]
Thanks @hsbadr, 

Will definitely use a variant but trying to avoid adding any more dependencies (I realise this is a bit late given how many we currently carry around) so will probably try and avoid piping (I think we currently avoid depending on `magrittr`?) and `stringr`.
